// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission06_jrencher.Models;

namespace mission06_jrencher.Migrations
{
    [DbContext(typeof(MovieResponseContext))]
    [Migration("20230421104525_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("mission06_jrencher.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Action/Adventure"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Family"
                        });
                });

            modelBuilder.Entity("mission06_jrencher.Models.MovieResponse", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Title");

                    b.HasIndex("CategoryId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            Title = "Antman and the Wasp",
                            CategoryId = 2,
                            Director = "Thanos",
                            Edited = true,
                            LentTo = "N/A",
                            Notes = "Funny",
                            Rating = "PG-13",
                            Year = 2016
                        },
                        new
                        {
                            Title = "Spiderman: No Way Home",
                            CategoryId = 1,
                            Director = "Wanda",
                            Edited = false,
                            LentTo = "Nathan",
                            Notes = "Best Movie Ever",
                            Rating = "PG-13",
                            Year = 2022
                        },
                        new
                        {
                            Title = "Endgame",
                            CategoryId = 1,
                            Director = "Thanos",
                            Edited = false,
                            LentTo = "N/A",
                            Notes = "So So Good",
                            Rating = "PG-13",
                            Year = 2016
                        });
                });

            modelBuilder.Entity("mission06_jrencher.Models.MovieResponse", b =>
                {
                    b.HasOne("mission06_jrencher.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
